baseURL = ""
languageCode = "en-us"
title = "Amelia Kwan"
theme = "hugo-PaperMod"

[markup.goldmark.renderer]
  tableOfContents = true

[frontmatter]
format = "yaml"

[params]
  homeInfoParams = { Title = "Hi, I'm Amelia", Content = "Welcome to my website - have a look around!" }

[[params.socialIcons]]
  name = "email"
  url = "mailto:atkwan76@gmail.com"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/amelia-kwan"
  
[[params.socialIcons]]
  name = "linkedin"
  url = "https://linkedin.com/in/amelia-kwan/"


[menu]
  main = [
    {identifier = "about", name = "about", url = "/about/", weight = 10 },
    {identifier = "experience", name = "experience", url = "/experience/", weight = 20},
    {identifier = "projects", name = "projects", url = "/projects/", weight =30}
  ]